### ISSUE TITLE
kotlinter not able to add spaces to indentation

### ISSUE THREAD

**Issue by henrik242** [jeremymailen/kotlinter-gradle#30] opened 2017-11-30 10:43 UTC
> Task :shared-http-client:formatKotlinMain 
    Format could not fix > src/main/java/Http.kt:56:1: Unexpected indentation (4) (it should be 8)

**Comment by jeremymailen** [comment] 2017-12-01 07:14
As you've noticed this is a side-effect of the underlying continuation indent support.
I'm assuming based on https://kotlinlang.org/docs/reference/coding-conventions.html you expected it to accept either normal indent (4) or the default continuation indent (8)?

I'll incorporate a new version of `ktlint` to get a fix when available. Thanks for bringing it to my attention!

**Comment by henrik242** [comment] 2017-12-01 08:11
I expected that it was actually able to automatically add whatever indentation that it couldn't fix.

**Comment by jeremymailen** [comment] 2018-01-19 17:06
@henrik242 I'm still keeping an eye on https://github.com/shyiko/ktlint/issues/116 and I'll grab the fix from upstream when available. Thanks for hanging in there.

**Comment by michaelbull** [comment] 2018-01-23 14:34
@jeremymailen looks like it was fixed & merged in https://github.com/shyiko/ktlint/pull/139

**Comment by jeremymailen** [comment] 2018-01-23 16:15
Yep 👍. I `ktlint` will push another release soon that includes it and then I'll do the same.

**Comment by DHuckaby** [comment] 2018-02-20 21:54
@jeremymailen `ktlint` has pushed version 0.15.1

https://github.com/shyiko/ktlint/releases

**Comment by shyiko** [comment] 2018-02-20 22:28
[ktlint#139](https://github.com/shyiko/ktlint/pull/139) is not included in ktlint@0.15.1 as it hasn't been properly tested. Once we're absolutely sure everything works the way it's supposed to and there are no regressions it will be released, hopefully as part of upcoming 0.16.0.

stability-first

**Comment by jeremymailen** [comment] 2018-02-21 06:39
Thank you @DHuckaby! I'll keep an eye out. Yes, as @shyiko points out the fix for this issue hasn't made it into a release yet, but I'll incorporate it when it's available.

**Comment by jeremymailen** [comment] 2018-02-28 07:00
It's in!

**Closed** 2018-02-28 06:59 UTC
