### ISSUE TITLE
ClassNotFoundException for LintWorkerRunnable

### ISSUE THREAD

**Issue by autonomousapps** [jeremymailen/kotlinter-gradle#116] opened 2019-08-21 19:01 UTC
Kotlinter 2.1.1
AGP 3.5.0
Gradle 5.6

This now happens every time we run `:lintKotlinAll` on CI (Jenkins). Not reproducible locally.

This didn't happen with AGP 3.5-rc2. Not sure what the root cause is. Any ideas?

the `:lintKotlinAll` task looks like this:
```
// root build.gradle
import org.jmailen.gradle.kotlinter.tasks.LintTask

def lintKotlinAll = tasks.register('lintKotlinAll', LintTask) {
    group = 'verification'
    source files(myProjects.collect { "${it.basePath}/src" })
    disabledRules = ["import-ordering", "final-newline"]
    reports = [
        'plain': file("$buildDir/reports/ktlint/all-lint.txt"),
        'html' : file("$buildDir/reports/ktlint/index.html")
    ]
}
```
where `myProjects` is an array of `MyProject` objects that simply represent all the Gradle subprojects in the build. So, one of the file elements would be `"app/src"`.
> [2019-08-21T17:33:12.426Z] FAILURE: Build failed with an exception.
> 
> [2019-08-21T17:33:12.426Z] 
> 
> [2019-08-21T17:33:12.426Z] * What went wrong:
> 
> [2019-08-21T17:33:12.426Z] Execution failed for task ':lintKotlinAll'.
> 
> [2019-08-21T17:33:12.426Z] > There were multiple failures while executing work items
> 
> [2019-08-21T17:33:12.426Z]    > A failure occurred while executing org.jmailen.gradle.kotlinter.tasks.lint.LintWorkerRunnable
> 
> [2019-08-21T17:33:12.426Z]       > java.lang.ClassNotFoundException: org.jmailen.gradle.kotlinter.tasks.lint.LintWorkerRunnable
> 
> [2019-08-21T17:33:12.426Z]    > A failure occurred while executing org.jmailen.gradle.kotlinter.tasks.lint.LintWorkerRunnable
> 
> [2019-08-21T17:33:12.426Z]       > java.lang.ClassNotFoundException: org.jmailen.gradle.kotlinter.tasks.lint.LintWorkerRunnable
> 
> [2019-08-21T17:33:12.426Z]    > A failure occurred while executing org.jmailen.gradle.kotlinter.tasks.lint.LintWorkerRunnable

... etc ...

**Comment by jeremymailen** [comment] 2019-08-23 08:27
Weird! So we're using the gradle worker api to launch the tasks and the runnable is on the other side of that. Not sure why it wouldn't be in the classpath. I assume that error is referring to the runnable class itself?

Jenkins might have the ability to distribute the tasks across nodes?
And you are executing it locally using the exact same gradle task and parameters?
At the time you upgraded the android plugin, did anything else get upgraded such as Gradle itself?

Just trying to find a direction to start digging.

**Comment by Naitbit** [comment] 2019-08-23 10:03
I've managed to reproduce this locally.

Just the AGP upgrade from
`com.android.tools.build:gradle:3.4.2`
to 
`com.android.tools.build:gradle:3.5.0`

It does not happen when `lintKotlinAll` is run as the only task, but it happens when it is run with other task that also uses workers. FE for me it happen both for `lintKotlinAll unitTestsWithCoverage` and for `lintKotlinAll lintDebug`. I suspect this is some kind off race condition if adding extra work to workers is required to reproduce it. 
Reproduced with 12 workers, 10 workers, 4 workers, and surprisingly even with 1. (via `--max-workers=1` flag)

I did run tasks later with `--no-daemon --rerun-tasks  clean` but this is not required. First failurewas without those flags. Those flags just make failures consistent (as they avoid task getting skipped due to UP-TO-DATE/FROM-CACHE states).

If you prepare some snapshot with extra logs I can rerun the builds on my project.

**Comment by jeremymailen** [comment] 2019-08-26 06:37
Thanks for all the hard work debugging. I think there are two things:
1. this pulls in a newer version of gradle worker api and our code needs to be updated to use it properly (old calls are deprecated
2. the worker action should probably use _classloader_ isolation instead of none

I was hoping to get the update out tonight, but having a bit of a wrestling match with the new worker api. Will try to get it done ASAP or if someone has time to contribute a PR I'll be happy to test and get it merged.

**Comment by Naitbit** [comment] 2019-09-02 10:11
I've made a quick naive check. Just changing isolationMode to `IsolationMode.CLASSLOADER` (in `LintWorkerConfigurationAction` `FormatWorkerConfigurationAction` results in test failures:
```
Caused by: java.util.NoSuchElementException: Key 7686d57a-b97f-4bb8-a34b-d8e8612077d8 is missing in the map.
	at kotlin.collections.MapsKt__MapWithDefaultKt.getOrImplicitDefaultNullable(MapWithDefault.kt:24)
	at kotlin.collections.MapsKt__MapsKt.getValue(Maps.kt:294)
	at org.jmailen.gradle.kotlinter.support.ExecutionContextRepository.get(ExecutionContextRepository.kt:34)
	at org.jmailen.gradle.kotlinter.tasks.lint.LintWorkerRunnable.<init>(LintWorkerRunnable.kt:21)
	at org.gradle.internal.instantiation.AsmBackedClassGenerator.newInstance(AsmBackedClassGenerator.java:153)
	at org.gradle.internal.instantiation.AbstractClassGenerator$GeneratedClassImpl$GeneratedConstructorImpl.newInstance(AbstractClassGenerator.java:389)
	at org.gradle.internal.instantiation.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:48)
	... 23 more
```
```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.jmailen.gradle.kotlinter.functional.FunctionalTest.lintKotlinMain fails when lint errors detected(FunctionalTest.kt:48)
```
I have little experience with Gradle plugins though so I may be missing something obvious.

**Comment by Naitbit** [comment] 2019-11-21 13:53
I did update to Kotlinter 2.1.3 with Gradle 5.6.2 and I can no longer reproduce the issue locally :+1:

**Comment by jeremymailen** [comment] 2019-11-22 01:58
Thanks for continuing the track this issue and the update! I'll close the issue based on your report and can reopen if someone else experience it in a different environment.

**Closed by jeremymailen** 2019-11-22 01:58 UTC
