### ISSUE TITLE
Kotlinter is not ignoring generated files

### ISSUE THREAD

**Issue by joshmsamuels** [jeremymailen/kotlinter-gradle#208] opened 2021-06-28 20:26 UTC
I have several generated kotlin files in my app (inside a `build` directory) which creates kotlin code that `ktlint` doesnt like. Since I have no control over the code generation and it is not being checked into git I would like ktlint to ignore the files within the `build` directory.

I tried adding several variations of `exclude("build/**")` but each time ktlint was failing on the generated files. Is there any way to ignore the `build` directory?

Note: I added the exclude directory to `"lintKotlinMain"(org.jmailen.gradle.kotlinter.tasks.LintTask::class) {` as stated in the README

Thanks so much!

**Comment by joshmsamuels** [comment] 2021-06-28 21:01
Since I wasnt sure the exact format expected, the other exclude variations I tried are:
```
exclude("**/build")
exclude("**/build/**")
exclude("build/***")
```

**Comment by jeremymailen** [comment] 2021-06-29 07:08
Thanks Josh, let me see if I can figure this one out.
If you navigate to the module in question and do `gradle tasks --all`, are there other `lintKotlinX` tasks for other sourceSets? It could be your generated files aren't in the "main" source set, but maybe another kotlinter detected.

Is that the same "build" directory as the one gradle uses for output?

The `LintTask` extends the standard Gradle `SourceTask` so `exclude` takes standard pattern arguments https://docs.gradle.org/current/dsl/org.gradle.api.tasks.SourceTask.html

**Comment by joshmsamuels** [comment] 2021-06-29 13:17
there is a `lintKotlin`, `lintKotlinMain`, and `lintKotlinTest` for each of the subprojects inside my main project.

> It could be your generated files aren't in the "main" source set, but maybe another kotlinter detected
kotlinter is only defined in the root project.

> Is that the same "build" directory as the one gradle uses for output?
Yes!

Thanks so much for the quick follow-up. I'm very new to kotlin so I may have done something wrong as well

**Comment by joshmsamuels** [comment] 2021-06-29 13:52
Based on [this issue in ktlint](https://github.com/JLLeitschuh/ktlint-gradle/issues/184) and the [ant pattern docs](http://ant.apache.org/manual/dirtasks.html#patterns) it looks like the correct syntax is `**/build/**` or  `**/build/` which should be equivalent.

@jeremymailen I tried both formats just now and they still didnt work 🙃

**Comment by jeremymailen** [comment] 2021-07-01 18:26
Can you show what the project structure looks like? Are these generated files being created by another gradle plugin or custom build code?

I ask because `build` seems unusual. Each of the kotlinter subtasks are associated with a sourceSet. For example the main source set for a project might have its root at `project/src/main/kotlin` and the exclude paths would be relative to that.
Kotlinter operates very similar to the gradle quality plugin which has some examples here: https://xvik.github.io/gradle-quality-plugin/2.4.0/guide/exclusion/

**Comment by joshmsamuels** [comment] 2021-07-03 17:37
is there a way to log the relative root for a source set?

**Comment by jeremymailen** [comment] 2021-07-05 16:54
You should be able to do something like this in your Gradle script
```kotlin
sourceSets.forEach {
    val dirPaths = it.java.srcDirs.map { d -> d.path }
    println("${it.name} : ${dirPaths.joinToString()}")
}
```
Kotlin JVM gradle plugin uses `java` sourceSet to configure things (see https://kotlinlang.org/docs/gradle.html#kotlin-and-java-sources).

Typically a standard project will have two sourceSets main and test. For kotlinter itself
```
main : /path/to/git/kotlinter-gradle/src/main/java
test : /path/to/git/kotlinter-gradle/src/test/java
```

**Comment by jeremymailen** [comment] 2021-07-05 16:55
Do you have any thoughts on the above questions -- what's generating your sources and your project structure?

**Comment by arnabkd** [comment] 2021-07-07 10:44
I have a similar problem (see image below):
![image](https://user-images.githubusercontent.com/1014699/124746042-bd21f980-df20-11eb-98e9-cbee621db06f.png)

My sources are being generated by Apollo Android and my project structure is like this:
```
/${projectDir}/src/main/kotlin <- where all the code resides for my app
/${projectDir}/src/test/kotlin <- tests
/${projectDir}/build/generated/... <- generated code from apollo android
```

**Comment by joshmsamuels** [comment] 2021-07-07 16:10
@jeremymailen where do I add that `sourceSets` block in the build.gradle.kts? `sourceSets` was not defined in the root, in tasks, or within the `lintTask`

**Comment by jeremymailen** [comment] 2021-07-18 22:48
Sorry, was out of town -- if you're still looking for a solution:
It occurs to me the easiest way to debug the problem is probably just debugging which files being linted:
```sh
gradle -d lintKotlin | grep linting
```

You'll see output including the relative file path and name of the lint task that is operating on it. For example:
```
2021-07-18T15:44:06.584-0700 [DEBUG] [org.jmailen.gradle.kotlinter.tasks.LintTask] lintKotlinTest linting: src/test/kotlin/org/jmailen/gradle/kotlinter/functional/KotlinProjectTest.kt
```

That's helpful info about the Apollo plugin. It looks like what it does is add a new path to each sourceSet under `build/generated`. For Apollo, did you try `exclude("**/generated/**")`?

**Comment by jeremymailen** [comment] 2021-07-18 23:26
Ok, did a few experiments with ordinary source sets. It appears the exclude path is oriented to the package, regardless of the root. For example to exclude my above file you'd need to:

```kotlin
tasks {
    "lintKotlinTest"(LintTask::class) {
        exclude("/org/jmailen/gradle/kotlinter/functional/KotlinProjectTest.kt")
    }
}
```
Or any glob including that exact path.

I know it's not the most user friendly when there's a whole root you need to exclude. Is there a pattern  within the package or file names you can target instead?

I suppose we could break our dependency on Gradle's `SourceTask` but would take some careful thought on how to extend it to add  something like `excludeSources`.

**Comment by arnabkd** [comment] 2021-07-19 22:30
``> Sorry, was out of town -- if you're still looking for a solution:
> It occurs to me the easiest way to debug the problem is probably just debugging which files being linted:
> 
> ```shell
> gradle -d lintKotlin | grep linting
> ```
> 
> You'll see output including the relative file path and name of the lint task that is operating on it. For example:
> 
> ```
> 2021-07-18T15:44:06.584-0700 [DEBUG] [org.jmailen.gradle.kotlinter.tasks.LintTask] lintKotlinTest linting: src/test/kotlin/org/jmailen/gradle/kotlinter/functional/KotlinProjectTest.kt
> ```
> 
> The key is to make sure you're modifying the excludes for the correct lint task and a matching path.
> 
> That's helpful info about the Apollo plugin. It looks like what it does is add a new path to each sourceSet under `build/generated`. For Apollo, did you try `exclude("**/generated/**")`?

I did try all of the variants that are described in the OP and with the generated blob as well:

```
exclude("**/build")
exclude("**/build/**")
exclude("build/***")

exclude("**/generated")
exclude("**/generated/**")
exclude("generated/***")
```

Those did not work. I am currently just contemplating running a ktlint check without the plugin, but it would be nice if the plugin was able to do this on its own.

**Comment by jeremymailen** [comment] 2021-07-19 22:53
> > Sorry, was out of town -- if you're still looking for a solution:
> > It occurs to me the easiest way to debug the problem is probably just debugging which files being linted:
> > ```shell
> > gradle -d lintKotlin | grep linting
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You'll see output including the relative file path and name of the lint task that is operating on it. For example:
> > ```
> > 2021-07-18T15:44:06.584-0700 [DEBUG] [org.jmailen.gradle.kotlinter.tasks.LintTask] lintKotlinTest linting: src/test/kotlin/org/jmailen/gradle/kotlinter/functional/KotlinProjectTest.kt
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The key is to make sure you're modifying the excludes for the correct lint task and a matching path.
> > That's helpful info about the Apollo plugin. It looks like what it does is add a new path to each sourceSet under `build/generated`. For Apollo, did you try `exclude("**/generated/**")`?
> 
> I did try all of the variants that are described in the OP and with the generated blob as well:
> 
> ```
> exclude("**/build")
> exclude("**/build/**")
> exclude("build/***")
> 
> exclude("**/generated")
> exclude("**/generated/**")
> exclude("generated/***")
> ```
> 
> Those did not work. I am currently just contemplating running a ktlint check without the plugin, but it would be nice if the plugin was able to do this on its own.

Ok, see my other note above -- it will work, but you must use a path matcher on the package or filename portion.

**Comment by arnabkd** [comment] 2021-07-19 23:24
> Ok, see my other note above -- it will work, but you must use a path matcher on the package or filename portion.

So with that I can just do the following?
```
tasks {
    "lintKotlinMain"(LintTask::class) {
        exclude("build/generated/source/apollo/main/service/*.kt")
    }
}
```

**Comment by jeremymailen** [comment] 2021-07-19 23:41
> > Ok, see my other note above -- it will work, but you must use a path matcher on the package or filename portion.
> 
> So with that I can just do the following?
> 
> ```
> tasks {
>     "lintKotlinMain"(LintTask::class) {
>         exclude("build/generated/source/apollo/main/service/*.kt")
>     }
> }
> ```

No you must use the package and filename portion of the path.

I'm just imagining how apollo might choose a package, but hopefully it's unique.
```kotlin
tasks {
    "lintKotlinMain"(LintTask::class) {
        exclude("service/graphql/*.kt")
    }
}
```

**Comment by arnabkd** [comment] 2021-07-19 23:49
> > > Ok, see my other note above -- it will work, but you must use a path matcher on the package or filename portion.
> > 
> > 
> > So with that I can just do the following?
> > ```
> > tasks {
> >     "lintKotlinMain"(LintTask::class) {
> >         exclude("build/generated/source/apollo/main/service/*.kt")
> >     }
> > }
> > ```
> 
> No you must use the package and filename portion of the path.
> 
> I'm just imagining how apollo might choose a package, but hopefully it's unique.
> 
> ```kotlin
> tasks {
>     "lintKotlinMain"(LintTask::class) {
>         exclude("service/graphql/*.kt")
>     }
> }
> ```

Ah ok, but apollo unfortunately does not create a package for anything but primitive types. So most of the generated classes are not in a package. In my case for instance, I simply do `import TripQuery` (which is where the generated code resides).

**Comment by jeremymailen** [comment] 2021-07-20 00:04
> Ah ok, but apollo unfortunately does not create a package for anything but primitive types. So most of the generated classes are not in a package. In my case for instance, I simply do `import TripQuery` (which is where the generated code resides).

It's looks like they provide a `rootPackageName`?
https://www.apollographql.com/docs/android/essentials/plugin-configuration/

Also seems like here:
https://www.apollographql.com/docs/android/essentials/get-started-kotlin/
```
apollo {
  packageName.set("com.example")
}
```

**Comment by arnabkd** [comment] 2021-07-20 00:09
> > Ah ok, but apollo unfortunately does not create a package for anything but primitive types. So most of the generated classes are not in a package. In my case for instance, I simply do `import TripQuery` (which is where the generated code resides).
> 
> It's looks like they provide a `rootPackageName`?
> [apollographql.com/docs/android/essentials/plugin-configuration](https://www.apollographql.com/docs/android/essentials/plugin-configuration/)
> 
> Also seems like here:
> [apollographql.com/docs/android/essentials/get-started-kotlin](https://www.apollographql.com/docs/android/essentials/get-started-kotlin/)
> 
> ```
> apollo {
>   packageName.set("com.example")
> }
> ```

Yes, it is possible to create one if required, but that's not the default configuration. Do I need to set a package name and *then* create the path?

**Comment by jeremymailen** [comment] 2021-07-20 00:23
I'm not an apollo user. I'm just noting in their docs you can change the package. I don't know their rationale for choose the root package as default.

Although Kotlinter wasn't designed specifically to support or not support apollo, I'm guessing any tool which generates source code will allow you to choose the output package because you'd need to be able to do that to prevent conflicts or control package visibility.

**Comment by RdeWilde** [comment] 2021-07-22 21:13
So from what I understand, the `exclude` is not matching the full path (as in the debug output `/build/generated/etc..`), but just the last part?

As an example, lint errors are here: `/Users/Robert/projects/core/common/build/generated/sqldelight/code/PeopleInSpaceDatabase/com/surrus/peopleinspace/db/*.kt`

This does not work/exclude the file(s):
```
tasks {
    "lintKotlinCommonMain"(org.jmailen.gradle.kotlinter.tasks.LintTask::class) {
        exclude("**/excluded/**")
    }
}
```
But this does:
```
tasks {
    "lintKotlinCommonMain"(org.jmailen.gradle.kotlinter.tasks.LintTask::class) {
        exclude("/com/surrus/peopleinspace/db/**")
    }
}
```

Can I somehow still match on the 'generated'-part? 
I think it is cleaner.

https://github.com/joreilly/PeopleInSpace/issues/64

**Comment by jeremymailen** [comment] 2021-07-22 21:27
You are correct @RdeWilde, the way `SourceTask` works is matching the package part of the path. I intend to clarify the documentation.
We would need to extend SourceTask and add another parameter to choose root trees to exclude as well.

It would be nice, but I wonder if we'll need it? It seems like any code generation plugin will allow you to specify a unique output package. Wouldn't you want a unique package anyway to keep your generated source separate in namespace from your hand written code?

**Comment by RdeWilde** [comment] 2021-07-22 21:35
That could be true. But basically I'd like to just exclude anything from the `generated`-path, no matter what package.

If it is too much hassle, this can also work. Suggestion not requirement :-)

**Comment by jeremymailen** [comment] 2021-07-22 22:41
Yes, will add it as an enhancement request. The Gradle Quality plugin has a similar extra param `excludeSources`
http://xvik.github.io/gradle-quality-plugin/4.6.0/guide/exclusion/

**Comment by jeremymailen** [comment] 2021-07-23 16:14
Closing for now and will take note of the enhancement request.

**Closed by jeremymailen** 2021-07-23 16:14 UTC

**Comment by joshmsamuels** [comment] 2021-08-05 15:22
Just catching up on this. Thanks @jeremymailen ! I got the exclude working now.

+1 to the enhancement discussed above, it would have been a more intuitive solution to discover and is better "documentation" that it is generated code being ignored.

**Comment by jeremymailen** [comment] 2021-08-05 17:35
Cool, noted. Glad you're able to find a solution for the meantime.

**Comment by zanonena** [comment] 2022-05-23 10:52
> Just catching up on this. Thanks @jeremymailen ! I got the exclude working now.
> 
> +1 to the enhancement discussed above, it would have been a more intuitive solution to discover and is better "documentation" that it is generated code being ignored.

Could you explain how you make it work?
Im facing the same issue, Im using a code generator plugin for my Graphql API (DGS codegen from netflix) and everything in goes into the /build/generated path outside the main project, and I cant make it work to ignore it, with ktlint gradle it works like a charm doing this:

ktlint {
    filter {
        exclude { element ->
            element.file.path.contains("generated/") ||
                element.file.path.contains("TestProjections") ||
                element.file.path.contains("build.gradle.kts")
        }
    }
}


But with this plugin it doesnt work at all

**Comment by raquezha** [comment] 2024-07-05 08:35
> > Just catching up on this. Thanks @jeremymailen ! I got the exclude working now.
> > +1 to the enhancement discussed above, it would have been a more intuitive solution to discover and is better "documentation" that it is generated code being ignored.
> 
> Could you explain how you make it work? Im facing the same issue, Im using a code generator plugin for my Graphql API (DGS codegen from netflix) and everything in goes into the /build/generated path outside the main project, and I cant make it work to ignore it, with ktlint gradle it works like a charm doing this:
> 
> ```
> ktlint {
>     filter {
>         exclude { element ->
>             element.file.path.contains("generated/")
>         }
>     }
> }
> ```
> 
> But with this plugin it doesnt work at all
> 
> We need a standard way to fix this problem...This issue must be open.
> 
> EDIT: Found a solution
> 
> ```
> tasks.formatKotlinMain {
>     exclude { it.file.path.contains("generated/")}
> }
> 
> tasks.lintKotlinMain {
>     exclude { it.file.path.contains("generated/")}
> }
> ```

Thanks this solves my problem!

**Comment by TrueFiskibility** [comment] 2024-08-29 18:04
Even more DRY:
```kotlin
import org.jmailen.gradle.kotlinter.tasks.ConfigurableKtLintTask

withType<ConfigurableKtLintTask> {
    exclude { it.file.path.contains("generated/") }
}
```
