### ISSUE TITLE
Kotlinter - configuring excluded files

### ISSUE THREAD

**Issue by Sethuraman** [jeremymailen/kotlinter-gradle#242] opened 2022-03-20 21:24 UTC
This is a follow up to the previously raised issue here - https://github.com/jeremymailen/kotlinter-gradle/issues/208

The issue is it is very hard to ignore files baed on the package name. There are 2 problems with this approach: 

1. The package name being ignored could be used in the src code as well. So you might inadvertently ignore code you wrote instead of ignoring just the ones that have been generated. 
2. At times when you are generating code for something such as protobufs, we pull in packages based on what the proto files depend on. Whenever a proto on a new package is pulled in, we need to edit the exclusions list again. 

It would be great to do a blanket exclusion of all files in the generated folder. 

Would be grateful to have the below config working: 

```
tasks.lintKotlinMain {
  exclude("**/generated/**")
}
```

**Comment by mateuszkwiecinski** [comment] 2022-03-21 22:15
Huh, I still haven't understood the root cause (the "the way SourceTask works is matching the package part of the path" part), but I can think of a workaround other than filtering by package:
```
tasks.named("lintKotlinMain") {
    source = source - fileTree("$buildDir/generated")
}
tasks.named("formatKotlinMain") {
    source = source - fileTree("$buildDir/generated")
}
```
It worked for me with apollo generated files, maybe it'll work for your case as well? 🤞 This doesn't rely on the `exclude` mechanism, but removes files under `/generated` a step earlier

**Comment by DevSrSouza** [comment] 2022-04-29 05:08
@jeremymailen any updates on this? the above solution did not work for me.

**Comment by zanonena** [comment] 2022-05-23 11:03
Im facing the same issue
I have my source project and outside my source poject in the build folder, im importing a lot of classed auto generated by a framework.
I cant find any way to ignore those files, in ktlint gradle I do this and it works, but here it doesnt:

filter {
        exclude { element ->
            element.file.path.contains("generated/")
        }
    }

Remember this classes and folder is in the build directory, and not in the main source path

**Comment by chrisjenx** [comment] 2022-09-13 14:32
Yes the FileTreeElement is probably what you want we do:
```
it.exclude { fte -> fte.file.absolutePath.contains("/build/") }
```

**Comment by jeremymailen** [comment] 2023-03-14 16:47
Ok, one style is now documented in the readme and it seems like people have ways to target the files they want. Closing for now.

**Closed by jeremymailen** 2023-03-14 16:47 UTC

**Comment by igorwojda** [comment] 2024-02-19 14:55
Exclude in Kotlin Gradle:
```kotlin
tasks.withType<LintTask> {
    exclude("**/KickAPI.kt")
}

tasks.withType<FormatTask> {
    exclude("**/KickAPI.kt")
}
```

**Comment by TrueFiskibility** [comment] 2024-08-29 18:02
Even more DRY:
```kotlin
import org.jmailen.gradle.kotlinter.tasks.ConfigurableKtLintTask

withType<ConfigurableKtLintTask> {
    exclude("generated/")
}
```

**Comment by Mahoney** [comment] 2025-03-13 10:09
FWIW:
```
tasks.withType<ConfigurableKtLintTask>().configureEach {
  val buildDirectory = layout.buildDirectory
  exclude {
    it.file.startsWith(buildDirectory.get().asFile)
  }
}
```
excludes any file in the build directory, which seems a good default to me.
